name = "utac-qa-calendar"
main = "worker/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "calendar-qa-db"
database_id = "11c524c4-b02e-4d38-840e-ee98294f2118" # Run: npx wrangler d1 create calendar-qa-db
